### ISSUE TITLE
Please explain more about the intention of Monad?

### ISSUE THREAD

**Issue by onmyway133** [JaviSoto/Blog-Posts#1]
> In the earlier example, we used the transformation function to return another value, but what if we wanted to use it to return a new Result object?

`func map<U>(f: T -> U) -> Result<U>`

What is the practical reason for which it returns `Result<U>` instead of `U`? We wrap `U` inside `Result` then `flatten` it, to get `U` again?

**Comment by JaviSoto** [comment]
`map` allows you to transform the object that you're calling it on. In this case it's a method on `Result`, so you wanna get another `Result`.
The practical reason is that `Result` doesn't _always_ contain a `U` inside, it may be an error. So every step of the way you wanna make sure you keep that error around. In the post, I return a `Result` object after reading a file, which may fail. When we transform that result object, for example, to turn the data inside into an `NSString` instance, and then to capitalize it, the initial value may have been nil (`.None`) all the way. `map` allows us to specify those transformations without having to do the `if error { } else { }` check every time.

Let me know if it doesn't make sense :)

**Comment by JaviSoto** [comment]
Oh, I noticed the title of your question is about `Monad`, but `map` is the function that turns out `Result` into a _Functor_. What makes it a `Monad` is the `flatMap` function I define later in the post.

**Comment by onmyway133** [comment]
thanks Javier

**Comment by JaviSoto** [comment]
Did it make sense? Don't be afraid to ask questions :)
