### ISSUE TITLE
innerResult?

### ISSUE THREAD

**Issue by jazzychad** [JaviSoto/Blog-Posts#3]
In the Monads section of the post, there is a code snippet where you define flatten, and inside there is a reference to `innerResult` - is this a typo? Or where is this coming from? Maybe this is some magic swift thing I am not familiar with? Very informative post, but this is tripping me up a bit. (I'm just starting to learn Swift, so maybe this is a language feature I haven't quite grasped yet.)

**Comment by JaviSoto** [comment]
Hey! :) Thanks for reading the post, and opening up an issue :)

`innerResult` is actually declared by the `let` in that line:

``` objc
case let .Value(innerResult):
```

This "unboxes" the value from the `Result.Value`, and gives it the `innerResult` name. Makes sense?

**Comment by jazzychad** [comment]
Ah ah, yes makes sense. Still getting used to the syntax in swift-land. Thanks for the post and the explanation.

**Comment by JaviSoto** [comment]
:+1:
